import { BACKGROUND } from './constants.js';

export const styles = {
  container: {
    backgroundColor: BACKGROUND,
    width: '100vw',
    height: '100vh',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'auto',
  },
  canvasWrapper: {
    flex: '1 1 0%',
    minHeight: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: '5%',
  },
  canvas: {
    backgroundColor: 'transparent',
  },
  helperText: {
    textAlign: 'center',
    color: '#aaa',
    fontSize: 12,
    fontWeight: 400,
    letterSpacing: 0.3,
    paddingTop: 4,
  },
  inputContainer: {
    padding: '16px 12px 40px',
    maxWidth: 400,
    width: '100%',
    alignSelf: 'center',
    margin: '0 auto',
  },
  inputRow: {
    display: 'flex',
    gap: 8,
    alignItems: 'center',
  },
  input: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 14,
    border: 'none',
    boxShadow: '0px 1px 4px rgba(0, 0, 0, 0.03)',
    color: '#1a1a1a',
    fontSize: 16,
    fontWeight: 400,
    letterSpacing: 0.2,
    padding: '14px 18px',
    outline: 'none',
    boxSizing: 'border-box',
    fontFamily: 'inherit',
    minWidth: 0,
  },
  submitBtn: {
    width: 48,
    height: 48,
    borderRadius: 14,
    border: 'none',
    backgroundColor: '#1a1a1a',
    color: '#fff',
    fontSize: 20,
    fontWeight: 600,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    transition: 'all 0.2s',
  },
  submitBtnDisabled: {
    backgroundColor: '#ccc',
    color: '#999',
    cursor: 'not-allowed',
  },
  inputError: {
    boxShadow: '0px 0px 0px 2px rgba(220, 80, 80, 0.3)',
  },
  errorText: {
    color: '#dc5050',
    fontSize: 12,
    fontWeight: 500,
    marginTop: 6,
    paddingLeft: 4,
  },
  seasonRow: {
    display: 'flex',
    gap: 6,
    marginTop: 10,
  },
  seasonBtn: {
    flex: 1,
    padding: '8px 4px',
    borderRadius: 10,
    border: 'none',
    backgroundColor: '#f0f0f0',
    color: '#555',
    fontSize: 12,
    fontWeight: 500,
    cursor: 'pointer',
    transition: 'all 0.2s',
    fontFamily: 'inherit',
  },
  seasonBtnActive: {
    backgroundColor: '#e8d5e0',
    color: '#1a1a1a',
    fontWeight: 600,
  },
  errorMessage: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    padding: 40,
    textAlign: 'center',
    color: '#666',
  },
};
